# Generated by Django 3.0.7 on 2020-06-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_auto_20200618_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='secondarySci',
            new_name='secondary',
        ),
    ]
