# Generated by Django 3.0.7 on 2020-06-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_auto_20200618_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondary',
            name='department',
            field=models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], default='science', max_length=10),
        ),
        migrations.AddField(
            model_name='secondary',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
