# Generated by Django 3.0.7 on 2020-06-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_auto_20200619_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary',
            name='department',
            field=models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('english', 'English'), ('readbook', 'Read Book')], default='science', max_length=10),
        ),
    ]
